# Generated by Django 2.2.9 on 2021-06-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trello", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column", name="title", field=models.CharField(max_length=256),
        ),
    ]
