# Generated by Django 2.2.9 on 2021-06-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trello", "0003_auto_20210622_1225"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="estimated_time",
            field=models.FloatField(blank=True, help_text="in minutes", null=True),
        ),
    ]
