# Generated by Django 2.2.9 on 2021-06-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trello", "0004_auto_20210622_1323"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="column", options={"ordering": ["position"]},
        ),
        migrations.AlterModelOptions(name="task", options={"ordering": ["position"]},),
    ]
